# Generated by Django 5.0.6 on 2024-07-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_systemsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SyatemSetting',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='map',
            field=models.URLField(blank=True, null=True),
        ),
    ]
