# Generated by Django 5.0.6 on 2024-07-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
    ]
