# Generated by Django 5.0.6 on 2024-07-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
